---
- name: Restart Postfix
  listen: postfix_config_added
  service:
    name: postfix
    state: restarted

- name: Register new aliases
  listen: aliases_added
  shell: newaliases

- name: Generate locales
  listen: locales_added
  locale_gen:
    name: '{{ item }}'
    state: present
  with_items: '{{ installed_locales }}'

- name: restart sshd
  service:
    name: '{{ sshd_service_name }}'
    state: restarted
  when: ssh_server_enabled | bool
  become: true