---
– hosts: all
sudo: yes
roles:
– { role: “ansible-role-ubuntu-stig-hardening”}

# crypto_ciphers
ssh_macs_53_default:
  - hmac-ripemd160
  - hmac-sha1

ssh_macs_53_el_6_5_default:
  - hmac-sha2-512
  - hmac-sha2-256

ssh_macs_59_default:
  - hmac-sha2-512
  - hmac-sha2-256
  - hmac-ripemd160

ssh_macs_66_default:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256

ssh_macs_76_default:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256

ssh_ciphers_53_default:
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

ssh_ciphers_66_default:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

ssh_kex_59_default:
  - diffie-hellman-group-exchange-sha256

ssh_kex_66_default:
  - curve25519-sha256@libssh.org
  - diffie-hellman-group-exchange-sha256

ssh_kex_80_default:
  - sntrup4591761x25519-sha512@tinyssh.org
  - curve25519-sha256@libssh.org
  - diffie-hellman-group-exchange-sha256

# auditd
## Audit daemon (auditd)
### Audit Tools
security_audit_tools:
  - /sbin/auditctl
  - /sbin/aureport
  - /sbin/ausearch
  - /sbin/autrace
  - /sbin/auditd
  - /sbin/audispd
  - /sbin/augenrules

### Send audit records to a different system using audisp.
security_audisp_remote_server: "10.0.0.2" # V-219162

### Audit Log
security_audit_log: "/var/log/audit/audit.log"
security_audit_log_directory: "/var/log/audit"

security_audit_directory: "/etc/audit"

### Banners
# V-219167
banner_message_text_gui: "'You are accessing a U.S. Government (USG) Information System (IS) that is \
    provided for USG-authorized use only. By using this IS (which includes any \
    device attached to this IS), you consent to the following conditions: -The USG \
    routinely intercepts and monitors communications on this IS for purposes \
    including, but not limited to, penetration testing, COMSEC monitoring, network \
    operations and defense, personnel misconduct (PM), law enforcement (LE), and \
    counterintelligence (CI) investigations. -At any time, the USG may inspect and \
    seize data stored on this IS. -Communications using, or data stored on, this \
    IS are not private, are subject to routine monitoring, interception, and \
    search, and may be disclosed or used for any USG-authorized purpose. -This IS \
    includes security measures (e.g., authentication and access controls) to \
    protect USG interests--not for your personal benefit or privacy. \
    -Notwithstanding the above, using this IS does not constitute consent to PM, \
    LE or CI investigative searching or monitoring of the content of privileged \
    communications, or work product, related to personal representation or \
    services by attorneys, psychotherapists, or clergy, and their assistants. Such \
    communications and work product are private and confidential. See User \
    Agreement for details.'"

# V-21970
banner_message_text_cli: "You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only. \
    By using this IS (which includes any device attached to this IS), you consent to the following conditions: \
    -The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations. \
    -At any time, the USG may inspect and seize data stored on this IS. \
    -Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose. \
    -This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy. \
    -Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details."
    
